naymspace/backpex

- lib/backpex/filters/boolean.ex
- lib/backpex/filters/multi_select.ex
- lib/backpex/filters/range.ex
- lib/backpex/filters/select.ex
We do not have the ability to override the `query/3` function for filters. So I added a `defoverridable` call to each filter. This gives more flexibility to the filters.
> Add ability to override `query/3` function in filters

- lib/backpex/fields/has_many.ex
- lib/backpex/fields/many_to_many.ex
In the `HasMany` and `ManyToMany` fields, if no LiveResource was configured, there were blocks of whitespace between elements in show view.
**Before**
**After**
> Fix whitespaces when no live resource is specified

- demo/lib/demo_web/live/home_live/index.html.heex
- lib/backpex/filters/multi_select.ex
To conform to the native HTML select (and backpex select filter), I changed the multi select filter width to `w-max`. This prevents long texts from wrapping.
> Adjust multi select filter width

- lib/backpex/live_components/form_component.ex
- lib/backpex/live_resource.ex
- lib/backpex/resource.ex
There is a case where we need to access a user in the changeset to validate permissions to change a particular field. In a Phoenix / LiveView application without Backpex, you could handle this case in the event handler before calling a changeset function. In Backpex we currently have no layer between the event and the changeset function. So we have to access the user via the assigns in the changeset function. We pass the `_target` to the changeset function for the same reason.
I suppose there is a better but more complex solution than passing all assigns to every function to handle such cases. Perhaps we should add more layers to hook into. We should address this in future updates!
> Pass assigns to changeset function

- lib/backpex/html/layout.ex
When using long names for field labels, the word does not break properly. Especially in the German language this is a problem. I have added a `hyphens-auto` class along with some padding to break words properly. This change requires the HTML `lang` attribute to be changed to the appropriate language.
Example:
> Improve breaking words

- lib/backpex/html/layout.ex
We had some strange behaviour in the `HasManyThrough` field that caused the linked values to reset when other form elements changed. This was the result of a change where we prevent the entire modal markup from rendering if it is not open. The way the `HasManyThrough` field currently works is that it stores the current state in the form inputs of the modal. This means that the modal markup has to be rendered even if if the modal is not open.
To prevent the Live View from crashing when certain keys are pressed when the modal is closed, we now conditionally assign these events based on the open state of the modal.
We should address this when reworking the `HasManyThrough` field.
> Render modal even if its not open

- lib/backpex/fields/number.ex
- lib/backpex/fields/text.ex
closes #61 
We now assign a unique identifier to each index form input based on the item id and the field name.
> Fix duplicated id for index form inputs

- demo/lib/demo/tag.ex
- demo/lib/demo_web/item_actions/duplicate_tag.ex
- demo/lib/demo_web/live/tag_live.ex
- lib/backpex/item_actions/item_action.ex
- lib/backpex/live_components/form_component.ex
Add `duplicate` action to tag resource.
> Add duplicate action

- demo/lib/demo/tag.ex
- demo/lib/demo_web/item_actions/duplicate_tag.ex
- demo/lib/demo_web/item_actions/soft_delete.ex
- guides/upgrading/v0.2.md
- lib/backpex/item_actions/item_action.ex
- lib/backpex/live_components/form_component.ex
- lib/backpex/live_resource.ex
- lib/backpex/resource_action.ex
With this PR we change the arity of the `init_change/0` function to `init_change/1` for resource and item actions.
The param will be the assigns. This adds more ways to construct an initial change.
> Change artity of init_change function and pass assigns

- .github/release.yml
Add `release.yml` with changelog configurations.
When the changelog is automatically generated, the pull request titles are sorted into different categories based on the labels defined in this file.
In addition to this PR, I *reworked* the labels.
See https://github.com/naymspace/backpex/labels
> Configure release notes

- lib/backpex/fields/select.ex
We used `Atom.to_string` before searching for a label in `Backpex.Fields.Select`. If the value was `nil` this caused the value to become "nil".  When we could not find an option with label "nil" we returned the value itself, so "nil" was displayed on show views.
> Fix nil value was not properly displayed in select field

- .github/workflows/ci.yml
- Dockerfile
- demo/assets/css/app.css
- demo/assets/tailwind.config.js
- demo/lib/demo/tag.ex
- demo/lib/demo_web/item_actions/duplicate_tag.ex
Many improvements for the CI pipeline.
We test Backpex in a separate matrix with different combination of OTP and Elixir version.
Along with that, we build a testing image based on the Dockerfile (`MIX_ENV=test`, `target=runtime`) and mostly use it to test the demo application. We run all lint commands provided in `demo/package.json`, compile the demo application with `--warnings-as-errors`, audit deps and run the tests. If all (demo) testing steps are successful, a runtime image is being built (`MIX_ENV=prod`, `target=runtime`).
The images are hosted in the GitHub Container registry:  https://github.com/orgs/naymspace/packages?repo_name=backpex We use [docker/metadata-action](https://github.com/docker/metadata-action) to label and tag the images. See the …
> Improve ci pipeline

- lib/backpex/fields/select.ex
- lib/backpex/live_resource.ex
Add `render_index_form` callback in order to support index editable for `Backpex.Fields.Select`
> Support index editable for Backpex.Fields.Select

- demo/lib/demo_web/live/home_live/index.html.heex
- mix.exs
- Change documentation entry point to `Backpex.LiveResource` module
- Replace documentation link with GitHub link on landing page
> Change documentation entry point and add github link to landing page

- lib/backpex/filters/boolean.ex
- lib/backpex/filters/multi_select.ex
- lib/backpex/filters/select.ex
If atoms were used as filter values, the filter label was not shown. This error occurred because we tried to compare atoms with strings in this case.
> Fix filter label is not displayed with atom values in filter options

- lib/backpex/resource.ex
If a field is found by `get_custom_alias` and no `custom_alias` is defined for that field, the function will return `nil`, which in some cases will break the query (e.g., if no `select` option is defined).
> Fix custom alias causes nil bindings in query

- demo/lib/demo_web/live/post_live.ex
- demo/lib/demo_web/live/product_live.ex
- lib/backpex/filters/filter.ex
- lib/backpex/html/resource.ex
Add the possibility to configure filter label in filter map / definition:
```elixir
@impl Backpex.LiveResource
def filters do
[
category_id: %{
module: MyAppWeb.Filters.Category,
label: "Category"
},
]
end
```
If no label is specified in the filter definition map, the label from the filter module is used. Therefore, this change is not breaking.
> Make filter label configurable in filter definition

- lib/backpex/fields/belongs_to.ex
- lib/backpex/fields/has_many.ex
- lib/backpex/fields/many_to_many.ex
- lib/backpex/fields/multi_select.ex
For some fields, the `truncate` class does not work properly in combination with `index_column_class` because the class is not applied to the root div of the live component.
> Fix truncate does not cut text in some fields

- lib/backpex.ex
Found via `typos --hidden --format brief`
> Fix typo, :genral -> :general

- lib/backpex/live_resource.ex
- lib/backpex/resource.ex
Resource show/edit fails when providing an incorrect `:id` in the path, because `Repo.get` just returns `nil` (for invalid UUIDs) or an cast error (for other invalid id strings).
> handle 404 for resource items

- .github/workflows/ci.yml
The release step fails because of untracked dependencies: https://github.com/naymspace/backpex/actions/runs/9496374080/job/26170659459
> Install deps during release step in ci

- README.md
There seems to have been a folder path change in the `guides` directory. This PR updates README.md to properly link to the `about` directory.
> Fix Learn More links in README

- README.md
We have to add `?raw=true` to GitHub image links to display them in hexdocs.
> Fix images are not displayed in docs

- demo/lib/demo_web/components/core_components.ex
- demo/lib/demo_web/components/layouts/root.html.heex
This PR removes `Phoenix.HTML.Tag` import in preparation for `phoenix_html` v4 upgrade.
> Turn sentry meta tag into component

- lib/backpex/live_components/form_component.ex
closes #316 
- Form error hint is now shown after first submit
- Validation hides form error hint
https://github.com/naymspace/backpex/assets/60519307/c666ee3d-f8d8-4372-8c86-10677e135082
> Fix form error hint is only shown after second submit

- guides/translations/translations.md
- lib/backpex/html/resource.ex
In #388 we provide a way to update create button labels. With the flexibility of Backpex, you could create nested index views. For example, an index live resource for posts associated with a user. In this case, instead of creating a new post on the posts resource, you would link existing posts to a user. While you can customize the label of the create button (see #388), the empty state says "Get started by **creating** new %{resources}", but it's not always about creating new resources. So this PR removes the empty state subtitle when no resources exist, to be more generic.
> Remove empty state subtitle when no resources exist

- demo/lib/demo_web/live/home_live/index.html.heex
Minor html improvement to remove linebreaks withing the PETAL acronym.
> Prevent PETAL from being split at linebreaks

- lib/backpex/fields/textarea.ex
Previously, newlines and spaces were collapsed in textarea values on show views. With this PR, textarea values are now displayed as in the input (show view only).
> Display newlines and whitespaces for textarea values

- guides/get_started/installation.md
- guides/get_started/prerequisites.md
- lib/backpex/item_actions/item_action.ex
- lib/backpex/resource_action.ex
- mix.exs
closes #403 
- Mention Alpine.js in prerequisites
- Improve installation guide
- Fix warnings when generating docs
- Replace deprecated `groups_for_functions` with `groups_for_docs`
> Improve documentation

- demo/lib/demo/product.ex
- demo/lib/demo_web/item_actions/duplicate_tag.ex
- demo/lib/demo_web/item_actions/soft_delete.ex
- demo/lib/demo_web/live/product_live.ex
- demo/lib/demo_web/live/user_live.ex
- demo/lib/demo_web/resource_actions/email.ex
- demo/lib/demo_web/resource_actions/upload.ex
- guides/actions/item-actions.md
- guides/actions/resource-actions.md
- guides/upgrading/v0.3.md
- guides/upgrading/v0.5.md
- lib/backpex/fields/upload.ex
- lib/backpex/item_actions/delete.ex
- lib/backpex/item_actions/edit.ex
- lib/backpex/item_actions/item_action.ex
- lib/backpex/item_actions/show.ex
- lib/backpex/live_components/form_component.ex
- lib/backpex/resource_action.ex
- mix.exs
- Pass persisted item with its changes to `consume_upload/4`.
- Pass `data` from `Ecto.Changeset.apply_changes/2`  instead of `params` to item action's `handle` function
- Pass `data` from `Ecto.Changeset.apply_changes/2`  instead of `params` to resource action's `handle` function
> Pass persisted item to `consume_upload` function and pass `data` to item actions and resource actions

- .github/workflows/ci.yml
Simplifies CI workflow and enables demo testing for external contributors.
- Use version-file feature in setup-beam action
- Remove building an image for testing
- Combine all demo testing jobs into one job
- Limit push trigger to `develop` and `main` branch
- Build and push runtime image on push only
> Update CI pipeline

- lib/backpex/html/resource.ex
Set a min and a max width for the toggle column dropdown truncating text that overflows, closes #166 .
> Fix toggle column width

- lib/backpex/resource.ex
Before this change when someone called the function with 5 arguments `FunctionClauseError` was risen.
> Fix `Backpex.Resource.update_all/6` when used without pubsub arg

- lib/backpex/live_components/form_component.ex
> Fix edit and new form crashes when all field fields are readonly

- lib/backpex/fields/has_many.ex
Add a match function that handles when `option.id` is represented as an integer in the HasMany field.
Closes #451 ?
> Add support for serial ids in HasMany field

- guides/get_started/installation.md
Noted during setup that lsp was complaining in the config about misplaced closing brackets, so made a quick fix here.
> Fix misplaced bracket in installation instructions

- lib/backpex/resource.ex
closes #530 
This PR checks for a named binding before joining. It prevents an error being thrown if a join with the same alias has already been performed, e.g. in the `item_query` function.
However, if we do not explicitly set an alias when joining in `item_query` this will **not** prevent a second join from being performed.
Consider a post belonging to a user. If we define an item query like this.
```elixir
@impl Backpex.LiveResource
def item_query(query, live_action, assigns) do
query
|> join(:left, [p], u in Demo.User, on: u.id == p.user_id)
end
```
`maybe_join` will do a second join because there is no alias `user` → `has_named_binding/2` returns false.
If we want to prevent a second join to be performed, we have to set the `user` alias explicitly:
```elixir
@impl …
```
> Check for named binding before joining

- lib/backpex/fields/number.ex
Fixed index_editable in Backpex.Fields.Number
When `index_editable: true` is set in the field with Backpex.Fields.Number, it will fail to update.
> Fixed index_editable in Backpex.Fields.Number

- .github/workflows/ci.yml
We always cache `deps` and `_build` directories. Therefore, I moved the two caching steps for `_build` and `deps` directories into one common caching step.
> Refactor caching steps in ci

- mix.exs
I think `.formatter.exs` was missing from the Hex package because formatting was not working in one of our projects.
> add formatter config to hex package

- .github/renovate.json
Renovate cannot update the base image because it can't pin the ubuntu image.
> WARN: Error updating branch: update failure (branch="renovate/base-image")
```json
{
"isPinDigest": true,
"updateType": "pinDigest",
"newValue": "jammy-20240808",
"newDigest": "sha256:adbb90115a21969d2fe6fa7f9af4253e16d45f8d4c1e930182610c4731962658",
"branchName": "renovate/base-image"
}
```
> Set `pinDigests` to false for ubuntu

- lib/backpex/fields/date.ex
- lib/backpex/fields/date_time.ex
Our current homespun admin panel has some custom logic based on `Timex` for formatting, which can't be replicated with `Calendar.strftime/2`. To resolve this, I made it possible to pass a function which formats the date or datetime.
We've started using Backpex for one admin page so far, looking to start using it for more! Thanks for your hard work and great project :smile:
> Allow passing a function to format a date or datetime

- .github/release.yml
- .github/renovate.json
I noticed that we have a "Dependency Updates" section in our release notes that includes both backpex and demo dependency updates. We should not include demo dependency updates there because they do not affect most users. I have added a new "Demo Dependency Updates" section and made some improvements to our release notes.
- Disable semantic commits for renovate (looks better in the changelog / release notes)
- Add `demo` label to dependency updates in /demo directory
- Add "Demo Dependency Updates" section to release notes
- Add descriptions to all renovate package rules
- Add `ignore-for-release` label to updates in `.github/workflows/ci.yml` (there is no need to include these udates in our release notes)
> Improve generated release notes

- guides/fields/custom-fields.md
- guides/fields/readonly.md
- guides/upgrading/v0.9.md
- lib/backpex/field.ex
- lib/backpex/fields/belongs_to.ex
- lib/backpex/fields/boolean.ex
- lib/backpex/fields/currency.ex
- lib/backpex/fields/date.ex
- lib/backpex/fields/date_time.ex
- lib/backpex/fields/has_many.ex
- lib/backpex/fields/has_many_through.ex
- lib/backpex/fields/inline_crud.ex
- lib/backpex/fields/number.ex
- lib/backpex/fields/select.ex
- lib/backpex/fields/text.ex
- lib/backpex/fields/textarea.ex
- lib/backpex/fields/upload.ex
- lib/backpex/fields/url.ex
- lib/backpex/html/form.ex
- mix.exs
closes #354 
I made `field_input` component more generic by not relying on a `field_options` map anymore. I also renamed the component to `input`.
- Rename `field_input` component to `input`
- Remove `field_options` attribute from `input` component
- Add `translate_error_fun` attribute for custom error translations
- Change type `string` to `any` for class attributes passed to `input` component (mainly to include lists, too)
- Refactor all `field_input` calls
> Refactor `field_input` component

- guides/get_started/installation.md
We do not implement an `item_query` function in our examples, so we have to remove this config.
> Fix incorrect configuration in installation guide

- demo/lib/demo/short_link.ex
- demo/priv/repo/migrations/20241112092150_drop_short_links_unique_index.exs
Currently, there is an error when submitting a short link with a URL suffix that already exists.
- Check for pkey unqiue constraint in changeset function
- Drop unique index as this is already covered by the pkey index
> Fix error when submitting short link with existing url suffix

- demo/lib/demo_web/live/post_live.ex
- lib/backpex/fields/textarea.ex
Add ‘rows' attribute to the textarea, with a default value of 3 rows.
> Add ‘rows' attribute to the textarea, with a default value of 2 rows.

- guides/upgrading/v0.9.md
- lib/backpex/adapters/ecto.ex
- lib/backpex/field.ex
- lib/backpex/fields/belongs_to.ex
- lib/backpex/fields/has_many.ex
- lib/backpex/html/resource.ex
- lib/backpex/html/resource/resource_index_table.html.heex
- lib/backpex/live_components/form_component.ex
- lib/backpex/live_resource.ex
see https://hexdocs.pm/credo/Credo.Check.Refactor.LongQuoteBlocks.html
- move everything from quote block to top level module in `Backpex.LiveResource`
- change some internal function to private; see f7f124b3edaa2e657ef7d296d158ac8c75878949
- remove `Backpex.LiveResource.schema/0` function; see 709bff8dac65ec135d6328d79fcd1c7ffb3ab8ef
- fix live updates for non-id primary keys; see dc051d2815bd364b32e43c2c296d4ee37eb03157
- remove obsolete `Backpex.LiveResource.can?/4` helper; see 9bdd735533a69ea51401bc7c2b8282acca949e7d and a4742105a06155e8d8da84d7084ff817ca2b5f16
- simplify active filters function; see 2aad9baa0d708e9d6bf93d3d7d9c09739dfcd7cd
- simplify `get_filter_options` function; see 2a43e79ea9e082272c731b592c739838452b4321
> Refactor Long Quote Block in LiveResource

- demo/lib/demo_web/item_actions/duplicate_tag.ex
- guides/upgrading/v0.9.md
- lib/backpex/item_actions/item_action.ex
- lib/backpex/live_components/form_component.ex
- lib/backpex/live_resource.ex
- lib/backpex/resource_action.ex
The term `init_change` is confusing because the result is used as the base schema / item for the changeset function.
> Rename item and resource action `init_change/1` callback to `base_schema/1`

- lib/backpex/live_resource.ex
Move `handle_event` and `handle_info` to `__before_compile__` block
> Fix custom `handle_event` and `handle_info` couldn't be defined in Live Resource

- guides/fields/custom-fields.md
- Add guide on how to add field options validation to custom fields
- Add note that custom fields might require adjustments because of breaking changes in the Backpex field API
> Improve custom fields docs

- lib/backpex/fields/upload.ex
- lib/backpex/live_components/form_component.ex
This fix the upload field not showing an error when saving by removing the `_unused_field` from the changes and letting Phoenix handle the error.
It still does not solve the caveat that removing an image does not show an error until you interact with another field (but sometimes it does when the user already has an image and you remove it).
> Fix empty upload not showing error on save

- lib/backpex/adapters/ecto.ex
- lib/backpex/live_resource.ex
a little bit of refactoring...
- removes obsolete `item_query` callback (was not used anymore)
- simplifies `list_query` function (in preparation to make it private or move metrics stuff)
> item_query refactoring

- lib/backpex/fields/upload.ex
I've been using a custom upload field with support for external uploads for a while, and after upgrading `Backpex`, I refactored my field and decided to extract the minimal functionality needed to support the existing Upload field.
The field works out of the box with Cloudflare R2 using the functions provided in the Phoenix LiveView documentation under [Direct to S3-Compatible External Uploads](https://hexdocs.pm/phoenix_live_view/external-uploads.html#direct-to-s3-compatible), but I would be more confident with the code if someone that uses S3 (or other external upload platforms) could test it as well.
If this is something that you're interested I can also update the documentation in this PR.
> Add external upload support for the Upload field.

- lib/backpex/live_resource.ex
- lib/backpex/router.ex
We did not pass the params to `get_path` in the default `return_to` implementation. This caused errors when nested routes were used (e.g., `/:id/users`). Besides passing the params, this PR also adds an understandable error message in case params are still missing to build route.
> Fix params not passed to `get_path` in default `return_to` route

- lib/backpex/fields/multi_select.ex
When returning non-string options, as shown in the example below:
```elixir
medical_specialties_input: %{
module: Backpex.Fields.MultiSelect,
label: gettext("Especialidades"),
options: fn _assigns ->
Accounts.list_medical_specialties()
|> Enum.map(&{&1.title, &1.id})
end
}
```
and error occurs:
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Backpex.HTML.Form.selected?/2
To make Backpex more robust, it’s essential to ensure that the returned options are converted to strings instead of raising this cryptic error.
> Fix MultiSelect crash when returning non strings as options

- demo/lib/demo_web/live/post_live.ex
- demo/lib/demo_web/live/user_live.ex
- lib/backpex/fields/boolean.ex
Okay, another simple change. I kind of find it's convenient to edit boolean fields  in the index(list) view. 
So I've added the 
```elixir
render_index_form(assigns)
```
and 
```elixir
handle_event("update-field", %{"index_form" => %{"value" => value}}, socket)
```
callbacks.
I've used a slightly smaller size toggle that you use in the `render_form` callback.
many thanks as usual for the great work.
> Add `index_editable` support for `Backpex.Fields.Boolean`

- lib/backpex/adapters/ecto.ex
Allow `select_merge` in `item_query` when `live_action` is `:index`. 
Before this change you cannot use `select_merge` on index because it collides with the count query for the pagination and results in the following error:
```
the following exception happened when compiling a subquery.
** (Ecto.QueryError) atoms, structs, maps, lists, tuples and sources are not allowed as map values in subquery, got: `%{child_count: {:subquery, 0}}` in query:
from v0 in MyApp.Parent,
as: :parent,
select: merge(v0, %{
child_count:
subquery(
#Ecto.Query<from a0 in MyApp.Child, where: a0.parent_id == parent_as(:parent).id, select: %{result: count()}>
)
})
The subquery originated from the following query:
from v0 in subquery(from v0 in MyApp.Parent,
as: :parent,
select: merge(v0, %{
child_count:
subquery( …
```
> Allow `select_merge` in `item_query` (index)

- lib/backpex/router.ex
closes #986 
This pull request includes changes to improve error handling in the `Backpex.Router` module by adding checks for missing routes and raising appropriate errors when routes are not found.
Improvements to error handling:
* [`lib/backpex/router.ex`](diffhunk://#diff-c6c09bf8961252686399d6a39c845d6e0b4c1655cae27cf0be52e2e44d260bc6L165-R178): Modified the `get_route_path` function to handle cases where a route is not found, raising an `ArgumentError` with a descriptive message.
* [`lib/backpex/router.ex`](diffhunk://#diff-c6c09bf8961252686399d6a39c845d6e0b4c1655cae27cf0be52e2e44d260bc6L219-R241): Updated the `cookie_path` function to raise an `ArgumentError` when the `backpex_cookies` route is missing, including instructions on how to add the route.
> Add error handling for missing routes in Router functions

- lib/backpex/html/form.ex
This fixes the validation not triggering when you click on a checkbox label:
> Fix checkbox validation not updating when clicking on checkbox label

- demo/lib/demo_web/live/film_review_live.ex
- demo/lib/demo_web/live/ticket_live.ex
- lib/backpex/html/layout.ex
- add flexible `alert/1` component with styles for `info`, `success`, `warning` and `error`
- fix styles (background + button hover) on error alerts (see below)
default:
button hover:
default:
button hover:
> fix and improve flash message styles and add alert component

- lib/backpex/fields/has_many.ex
If there are no options for the `HasMany`, errors are displayed immediately after any form input is used.
I guess, the reason is that no checkboxes are rendered in this case expect from the hidden input.
Hiding the hidden input with CSS and removing `type="hidden"` resolves the issue.
https://github.com/user-attachments/assets/f2115de1-244e-42de-82ee-48a914e3f990
> Fix `HasMany` shows error if input was not used yet

- lib/backpex/field.ex
If the index view had editable fields, the layout would shift when the resource action modal was opened because the inputs were only shown for `:index` `live_action`, not `:resource_action`.
See the upload action in the latest demo: https://demo.backpex.live/admin/users
> Fix index edit not shown behind resource action modal

- guides/fields/readonly.md
- guides/upgrading/v0.14.md
- lib/backpex/field.ex
- lib/backpex/fields/date.ex
- lib/backpex/fields/date_time.ex
- lib/backpex/fields/number.ex
- lib/backpex/fields/text.ex
- lib/backpex/fields/textarea.ex
- lib/backpex/fields/time.ex
- lib/backpex/html/resource.ex
You can mark a field as read-only. In our field implementations, we have a dedicated `render_form_readonly/1` callback that returns read-only markup. This is simply a copy of the normal `render_form` version with some additional attributes. This MR passes a `readonly` assign to `render_form` to render these attributes conditionally. You would need to handle a read-only state in the same way for `render_index_form`.
With this change we can remove some duplicated code.
In case you have a more complex read-only version, e.g. in custom fields, you can just pattern match and define a dedicated function like before:
```elixir
@impl Backpex.Field
def render_form(%{readonly: true} = assigns) do
end
def render_form(assigns) do
end
```
> Remove `render_form_readonly` callback from fields

- lib/backpex/adapters/ecto.ex
- test/adapters/ecto_test.exs
closes #562 
We did not skip applying the search conditions if the search string was empty (`""`).
This resulted in conditions such as `ilike(a0.city, "%%")`being applied. While this was OK for string values, it excluded `NULL` values.
The solution is to skip applying search conditions when the search string is empty.
The fix can be tested by making the `address.city` field nullable and disabling search for all `adress` fields except for the `city` field.
> Fix entries were excluded from index view under certain conditions

- lib/backpex/filters/multi_select.ex
Hi all,
it seems the `query` function in `Backpex.Filters.MultiSelect` is overly complicated, and can be rewritten in just a one-liner. I have also renamed the argument `value` to `values` for better coherence.
Hope this helps!
> Simplify query function in MultiSelect filter

- lib/mix/tasks/backpex.install.ex
> Auto-detect app.js or app.ts in `backpex.install` task
