lib/backpex/html/form.ex

Add value to select field input options to add the ability to set the selected value.

Use value in select field input

---

lib/backpex/live_resource.ex

An error occurs if an item is updated while the show view is open. In this case we are trying to update the list of items, but there is no `items` key.
With this merge request, the `handle_info` callback takes into account the live action. It also fetches the item from the database to properly load all associations. Previously the `HasManyThrough` field value was not correctly updated by pub sub events.

Fix updating item on show view

---

lib/backpex/fields/date.ex
lib/backpex/fields/date_time.ex
lib/backpex/fields/number.ex

Suppport `readonly` option for Date, DateTime and Number field.

Add readonly to Date, DateTime and Number field

---

guides/upgrading/v0.2.md
lib/backpex/fields/belongs_to.ex
lib/backpex/fields/has_many.ex
lib/backpex/fields/many_to_many.ex
lib/backpex/fields/multi_select.ex
lib/backpex/fields/select.ex

- Allow prompt option to be a function that receives the assigns
- Add hint to upgrade guide to update prompt option for fields

Improve prompt option

---

.github/release.yml

Changes to the documentation should be included in the release notes.

Add documentation pull requests to release notes

---

lib/backpex/live_resource.ex

We have accidentally removed the "New".

Add missing "New" in created message

---

lib/backpex/html/resource.ex

Fixes issues introduced with the heroicons update.

Fix filter badge close icon

---

demo/lib/demo_web/endpoint.ex
demo/lib/demo_web/router.ex

see https://hexdocs.pm/sentry/Sentry.LiveViewHook.html

Demo: improve Sentry data

---

lib/backpex/html/resource.ex

Fix column toggle labels not clickable 

---

lib/backpex/fields/has_many.ex
lib/backpex/fields/multi_select.ex

Fix HasMany and MultiSelect search field not working

---

demo/package.json
demo/yarn.lock

Fixes daisyUI unmet peer dependency warning in demo

Install postcss in demo application

---

guides/actions/item-actions.md

Remove show item action placement from docs

---

.docker/etc/bash.bashrc
.docker/etc/bashrc.d/prompt.sh
.docker/root/.bashrc
.github/renovate.json
.github/workflows/ci.yml
Dockerfile

- Remove bashrc stuff
- Switch from alpine to ubuntu
- Configure `renovate.json` to properly update elixir base image

Switch from Alpine to Ubuntu

---

.credo.exs
demo/lib/demo/short_link.ex
demo/lib/demo_web/item_actions/soft_delete.ex
lib/backpex/adapters/ecto.ex
lib/backpex/fields/has_many.ex
lib/backpex/live_resource.ex
test/doc_test.exs

- enable all credo checks by default
- overwrite (disable or reconfigure) credo checks explicitly
- implement some easy credo checks and fixes

improve credo config

---

mix.exs

Loosen version requirements to fix dependency resolution.

Update version strings in `mix.exs`

---

Dockerfile

see https://github.com/naymspace/backpex/actions/runs/12944555611/job/36105803565

Fix warning in Dockerfile

---

.github/release.yml
.github/renovate.json

- Automerge all patch updates
- Remove demo dependency updates from changelog

Update renovate config

---

lib/backpex/fields/upload.ex

https://github.com/user-attachments/assets/93151fd8-6e47-4c02-914c-1a3b4e88e09a

add upload progress indicator

---

lib/backpex/fields/textarea.ex

Assign missing rows in readonly textarea field

---

lib/backpex/fields/has_many_through.ex
lib/backpex/fields/upload.ex
lib/backpex/html/resource.ex

This needed to make multiple uploads per field work.

assign all @uploads to field

---

guides/get_started/installation.md

Improve installation guide

---

lib/backpex/html/form.ex

Add option to disable multi select search input

---

lib/backpex/fields/belongs_to.ex
lib/backpex/fields/date.ex
lib/backpex/fields/date_time.ex
lib/backpex/fields/number.ex
lib/backpex/fields/select.ex
lib/backpex/fields/text.ex
lib/backpex/fields/time.ex

See https://tailwindcss.com/blog/tailwindcss-v4#not-variant

Update code to use the new Tailwind CSS `not-*` variant

---

guides/upgrading/v0.14.md
lib/backpex/fields/belongs_to.ex
lib/backpex/fields/boolean.ex
lib/backpex/fields/select.ex
lib/backpex/html/form.ex

Update `Backpex.HTML.Form.input/1` to align with the *new* [Phoenix CoreComponents](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L170).

Update `input/1` component

---

lib/backpex/live_resource/index.ex

Show plural name as page title for resource actions

---

guides/live_resource/on_mount-hook.md
lib/backpex/item_actions/delete.ex
lib/backpex/item_actions/edit.ex

Fix some errors in the documentation

Fix some errors in the documentation

---

guides/fields/index-edit.md
guides/fields/what-is-a-field.md
lib/backpex/fields/email.ex

I wanted a field that had a proper email input on mobile - not sure if you had a different way you wanted to do this

Add `Backpex.Fields.Email`

---

lib/backpex/html/form.ex

Reverts naymspace/backpex#1544

Revert "Fix picker appearance for select input"
